# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Category.create(name:"小学校")
Category.create(name:"中学校")
Category.create(name:"高校")
Category.create(name:"大学")
Category.create(name:"社会人")

Region.create(name: "北海道")
Region.create(name: "青森県")
Region.create(name: "岩手県")
Region.create(name: "宮城県")
Region.create(name: "秋田県")
Region.create(name: "山形県")
Region.create(name: "福島県")
Region.create(name: "茨城県")
Region.create(name: "栃木県")
Region.create(name: "群馬県")
Region.create(name: "埼玉県")
Region.create(name: "千葉県")
Region.create(name: "東京都")
Region.create(name: "神奈川県")
Region.create(name: "新潟県")
Region.create(name: "富山県")
Region.create(name: "石川県")
Region.create(name: "福井県")
Region.create(name: "山梨県")
Region.create(name: "長野県")
Region.create(name: "岐阜県")
Region.create(name: "静岡県")
Region.create(name: "愛知県")
Region.create(name: "三重県")
Region.create(name: "滋賀県")
Region.create(name: "京都府")
Region.create(name: "大阪府")
Region.create(name: "兵庫県")
Region.create(name: "奈良県")
Region.create(name: "和歌山県")
Region.create(name: "鳥取県")
Region.create(name: "島根県")
Region.create(name: "岡山県")
Region.create(name: "広島県")
Region.create(name: "山口県")
Region.create(name: "徳島県")
Region.create(name: "香川県")
Region.create(name: "愛媛県")
Region.create(name: "高知県")
Region.create(name: "福岡県")
Region.create(name: "佐賀県")
Region.create(name: "長崎県")
Region.create(name: "熊本県")
Region.create(name: "大分県")
Region.create(name: "宮崎県")
Region.create(name: "鹿児島県")
Region.create(name: "沖縄県")

Team.create(name: "ホンマでっか!?", region_id: 40, category_id: 3)
Team.create(name: "イーグルス", region_id: 12, category_id: 2)
Team.create(name: "府中ビッグ", region_id: 13, category_id: 1)
Team.create(name: "イカリング", region_id: 1, category_id: 5)
Team.create(name: "たこザンギ", region_id: 1, category_id: 4)
